USE [master]
GO

/****** Object:  Database [PlayerAssociation]    Script Date: 12/29/2025 12:08:22 PM ******/
CREATE DATABASE [PlayerAssociation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PlayerAssociation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PlayerAssociation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PlayerAssociation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PlayerAssociation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PlayerAssociation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PlayerAssociation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PlayerAssociation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PlayerAssociation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PlayerAssociation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PlayerAssociation] SET ARITHABORT OFF 
GO

ALTER DATABASE [PlayerAssociation] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PlayerAssociation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PlayerAssociation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PlayerAssociation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PlayerAssociation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PlayerAssociation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PlayerAssociation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PlayerAssociation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PlayerAssociation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PlayerAssociation] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PlayerAssociation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PlayerAssociation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PlayerAssociation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PlayerAssociation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PlayerAssociation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PlayerAssociation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PlayerAssociation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PlayerAssociation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PlayerAssociation] SET  MULTI_USER 
GO

ALTER DATABASE [PlayerAssociation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PlayerAssociation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PlayerAssociation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PlayerAssociation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PlayerAssociation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PlayerAssociation] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PlayerAssociation] SET  READ_WRITE 
GO

